events {}

http {
  upstream service_a {
    server service-a:4000;
  }

  upstream service_b {
    server service-b:4001;
  }

  upstream service_c {
    server service-c:4002;
  }

  server {
    listen 80;

    location /service-a/ {
      proxy_pass http://service_a/;
    }

    location /service-b/ {
      proxy_pass http://service_b/;
    }

    location /service-c/ {
      proxy_pass http://service_c/;
    }
  }
}